[versions]
assertj-core = "3.27.6"
commons-text = "1.15.0"
jsonpathkt = "2.0.1"
jsoup = "1.21.2"
junit-jupiter = "6.0.1"
junit-platform-launcher = "6.0.1"
kommand = "1.4.10"
kotlin = "2.2.21"
kotlinx-coroutines-core-jvm = "1.10.2"
kover = "0.9.4"
logback-classic = "1.5.22"
moshi = "1.15.2"
okhttp = "5.3.2"
slf4j-api = "2.0.17"
tomlj = "1.1.1"
wiremock = "3.13.2"
zstandard = "1.5.7-6"
slf4j-jul-to-slf4j = "2.0.17"


[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
jsonpathkt = { module = "com.nfeld.jsonpathkt:jsonpathkt", version.ref = "jsonpathkt" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform-launcher" }
kommand = { module = "io.github.manamiproject:kommand", version.ref = "kommand" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines-core-jvm" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
slf4j-jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j-jul-to-slf4j" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
zstandard = { module = "com.github.luben:zstd-jni", version.ref = "zstandard" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
shadow = { id = "com.gradleup.shadow", version = "9.3.0" }

[bundles]